// <auto-generated />
namespace react_mvc.DBContexts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updateofinitialtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updateofinitialtables));
        
        string IMigrationMetadata.Id
        {
            get { return "201603281729301_Update of initial tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
